debug: true

logging:
  level:
    root: ERROR
    org:
      springframework:
        security: ERROR

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
#    url: jdbc:mysql://192.168.1.106:3306/registry_mgr?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql:3306/registry_mgr?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: toor
    password: jnEhO5Dhk7U5ou9GFs95dmPdwrmVhigC
    driver-class-name: com.mysql.cj.jdbc.Driver